### PR TITLE
Abb

### PR DESCRIPTION
**Pull request by atulbhingarde**
added logic for counting total attempts and correct attempts 
added logic for selecting 4 out 10 and getting another 10 out of 200 or so and continue playing.

### CODE REVIEW

**Comment by atulbhingarde** [comment]
please merge the latest code it has more robust logic than previous one , if you want to check the site https://atulbhingarde.github.io/test123/ before merging it would be helpful

**Comment by atulbhingarde** [comment]
new pull request from abb for lats updated logic

**Comment by atulbhingarde** [comment]
One more change to correct logic for string match.

**Comment by mhigh1** [comment]
pull request superceeded by #8

**Pull request closed without merging**
